/*
Deployment script for E:\PROJECTS\DEVELOPING\CSHARP\THEMEDIT\THEMEDIT\THEMEDIT.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "E:\PROJECTS\DEVELOPING\CSHARP\THEMEDIT\THEMEDIT\THEMEDIT.MDF"
:setvar DefaultFilePrefix "E_\PROJECTS\DEVELOPING\CSHARP\THEMEDIT\THEMEDIT\THEMEDIT.MDF_"
:setvar DefaultDataPath "C:\Users\Softbery\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\Softbery\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
END


GO
USE[$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[LastSettings].[Key] (SqlSimpleColumn) will not be renamed to MediaPath';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[LastSettings].[Value] (SqlSimpleColumn) will not be renamed to VolumeLevel';


GO

IF(SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors(Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating Table [dbo].[LastSettings]...';


GO
CREATE TABLE[dbo].[LastSettings](
    [Id]             INT            NOT NULL,
    [VolumeLevel]    NVARCHAR(MAX) NULL,
    [Playlist]       NTEXT          NULL,
    [MediaPath]      NVARCHAR(MAX) NULL,
    [MediaPosition]  TIMESTAMP      NULL,
    [SubtitlesPath]  NVARCHAR(MAX) NULL,
    [SubtitlesOnOff] TINYINT        NULL,
    [UrlAddress]     NVARCHAR(MAX) NULL,
    [WindowPosition] NVARCHAR(50)  NULL,
    [WindowStatus]   NCHAR(20)     NULL,
    [RichTextBoxLog] NTEXT          NULL,
    PRIMARY KEY CLUSTERED([Id] ASC)
);


GO
IF @@ERROR<>0
   AND @@TRANCOUNT > 0
BEGIN
ROLLBACK;
END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE[#tmpErrors](
    Error INT
);

IF @@TRANCOUNT = 0
BEGIN
        INSERT  INTO #tmpErrors(Error)
VALUES(1);
        BEGIN TRANSACTION;
END


GO

IF EXISTS(SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT> 0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
IF(SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
GO
PRINT N'Update complete.';


GO
